ethereum_rpc = "https://ethereum-holesky-rpc.publicnode.com"
drosera_rpc = "https://seed-node.testnet.drosera.io"
eth_chain_id = 17000
drosera_address = "0xea08f7d533C2b9A62F40D5326214f39a8E3A32F8"

[traps]

[traps.protocol]
path = "out/ProtocolTrap.sol/ProtocolTrap.json"
response_contract = "0x4603b254ca806aDAFd52A35f5a8c5a97743df342"
response_function = "pause()"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
address = "0x80e0E67498Bf1BB6C2fb6499E94fafC2e8Aa0050"
