[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
script = 'scripts'
solc_version = '0.8.19'
extra_output = [
  "abi",
  "evm.bytecode",
  "evm.deployedBytecode",
  "evm.methodIdentifiers",
]
optimizer = true
optimizer_runs = 20_000
force = false
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "https://eth.ubq.fi/v1/mainnet"
