[default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = ['forge-std/=lib/forge-std/src/', '@openzeppelin/=node_modules/@openzeppelin/']
solc = "0.8.10"
bytecode_hash = "none"
optimizer_runs = 1000000

[intense]
fuzz_runs = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config