name: Continuous Deploy

on:
  workflow_run:
    workflows: ["Build & Test"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: "Download Artifact"
        uses: actions/github-script@v6.3.3
        with:
          script: |
            const fs = require("fs");
            const download_artifact = require('${{ github.workspace }}/utils/download_artifact.js');
            const workflow_run_id = '${{ github.event.workflow_run.id }}';
            const workspace = '${{ github.workspace }}';
            download_artifact({github, context, fs, workflow_run_id, workspace})

      - name: Extract Artifact
        run: unzip pr.zip && unzip pull-request.zip && ls

      - name: Deploy Netlify
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID_DEVELOPMENT }}
          netlify deploy --dir=./dist --prod > ./deployments.log
          ls -la

      - name: Deploy Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ubiquity-dollar
          directory: ./dist

      - name: Get UbiquiBot Token
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.UBIQUITY_BOUNTY_BOT_APP_ID }}
          private_key: ${{ secrets.UBIQUITY_BOUNTY_BOT_PRIVATE_KEY }}

      - name: Save UbiquiBot Token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"

      - name: Deploy Comment as UbiquiBot
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_installation_token.outputs.token }}
          script: |
            const fs = require("fs");
            const print_deployments_log = require('${{ github.workspace }}/utils/print_deployments_logs.js');
            await print_deployments_log({github, context, fs});
