name: Conventional Commits

on:
  pull_request:
  push:
    branches: [development]

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ubiquity/action-conventional-commits@v1.1.2
