# GitHub Action to build Dapp before deploying on Hosting Service
name: Build Dapp
on:
  push:
    branches:
      - githubActionToFleekHosting
      # - main

jobs:
  check:
    name: Build Dapp, ready to be deployed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install node and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Build Dapp
        run: yarn && yarn build:dapp
        # env:
        #   API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
        #   API_KEY_COINMARKETCAP: ${{ secrets.API_KEY_COINMARKETCAP }}
        #   API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
        #   MNEMONIC: ${{ secrets.MNEMONIC }}

      - name: Delete .gitignore to include web/dapp in commit
        run: rm web/.gitignore

      - name: Commit Dapp build
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add web/dapp
          git commit -am "${{ github.ref_name }} dapp build !"

      - name: Push Dapp build
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build/${{ github.ref_name }}
          force: true
          directory: "web/dapp"
