name: Deep Fuzz and Invariant Tests
on:
  push:
    branches:
      - development
    paths:
      - '**.sol'

jobs:
  deep-fuzz-and-invariant:
    name: Run Deep Fuzz and Invariant Tests
    runs-on: ubuntu-22.04
    env:
      FOUNDRY_PROFILE: intense

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-5be158ba6dc7c798a6f032026fe60fc01686b33b

      - name: Forge install
        working-directory: packages/contracts
        run: forge install

      - name: Run Deep Fuzz and Invariant Tests
        working-directory: packages/contracts
        run: forge test
