name: Development to Development-CI Sync

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync changes from development to development-ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"

      - name: Create development-ci branch if it doesn't exist and sync to the latest remote branch
        run: |
          git branch | grep -q 'development-ci' || git branch development-ci
          git checkout development-ci
          git pull origin

      - name: Merge changes from development
        run: |
          git merge development | echo "No changes to merge"

      - name: Push changes to development-ci
        run: |
          git push origin development-ci
