name: Install and Build Workflow for Pull Request

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  create:
    tag:
      - "v*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # - name: Install OS Dependencies
      #   run: sudo apt -y install libusb-1.0-0-dev libudev-dev

      # - name: Ubiquity Dollar CI/CD
      #   run: yarn build:cd

      # - name: Save as Zip File Artifact
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     mkdir -p ./pr
      #     echo $PR_NUMBER > ./pr/pr_number
      #     zip -r pull-request.zip ./dist
      #     zip -d pull-request.zip dist/ubiquity-one-fifth-speed-trimmed-compressed.mp4
      #     cp pull-request.zip ./pr
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: pr
      #     path: pr/
