name: Receive workflow and Deploy

on:
  workflow_run:
    workflows: ["Install and Build Workflow"]
    types:
      - completed

jobs:
  receive-pr-and-deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Download artifact"
        uses: actions/github-script@v3.1.0
        with:
          script: |
            const fs = require("fs");
            const download_artifact = require('${{ github.workspace }}/bin/download_artifact.js');
            const workflow_run_id = '${{ github.event.workflow_run.id }}';
            const workspace = '${{ github.workspace }}';
            download_artifact({github, context, fs, workflow_run_id, workspace})
      - name: Extract files
        run: unzip pr.zip && unzip pull-request.zip && ls

      - name: Deploy Development
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID_DEVELOPMENT }}
          netlify deploy --dir=./dist --prod > ./deployments.log

      - name: Print Logs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const print_deployments_log = require('${{ github.workspace }}/bin/print_deployments_logs.js');
            await print_deployments_log({github, context, fs});
