name: Received PR and Deploy

on:
  workflow_run:
    workflows: ["Install and Build Workflow for Pull Request"]
    types:
      - completed

jobs:
  receive-pr-and-deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: "Download Zip File Artifact"
        uses: actions/github-script@v3.1.0
        with:
          script: |
            const RUN_ID = ${{ github.event.workflow_run.id }};
            const downloadArtifact = require("path").join(".github", "workflows", "download-artifact.js");
            console.log(process.cwd());
            require("./".concat(downloadArtifact))(github, context, RUN_ID);

      - name: Extract Files
        run: |
          unzip pr.zip
          unzip pull-request.zip
          ls

      - name: Deploy Preview
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID_DEVELOPMENT }}
          netlify deploy --prod > ./deployments.log

      - name: "Comment on PR"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          script: |
            const commentOnPr = require("path").join(".github", "workflows", "comment-on-pr.js");
            console.log(process.cwd());
            require("./".concat(commentOnPr))(github, context);