name: Received PR and Deploy

on:
  workflow_run:
    workflows: ["Install and Build Workflow for Pull Request"]
    types:
      - completed

jobs:
  receive-pr-and-deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Download Zip File Artifact"
        uses: actions/github-script@v6.1.0
        with:
          debug: true
          script: |

            var fs = require('fs');
            var path = require('path');
            var walk = function(dir, done) {
              var results = [];
              fs.readdir(dir, function(err, list) {
                if (err) return done(err);
                var i = 0;
                (function next() {
                  var file = list[i++];
                  if (!file) return done(null, results);
                  file = path.resolve(dir, file);
                  fs.stat(file, function(err, stat) {
                    if (stat && stat.isDirectory()) {
                      walk(file, function(err, res) {
                        results = results.concat(res);
                        next();
                      });
                    } else {
                      results.push(file);
                      next();
                    }
                  });
                })();
              });
            };

            walk(${{github.workspace}}, function(err, results) {
              if (err) throw err;
              for (const result of results){
                console.log(result);
              }
            });



            const RUN_ID = ${{ github.event.workflow_run.id }};
            const downloadArtifact = require("path").join(${{github.workspace}}, ".github", "workflows", "download-artifact.js");
            console.log(process.cwd());
            require("./".concat(downloadArtifact))(github, context, RUN_ID);

      - name: Extract Files
        run: |
          unzip pr.zip
          unzip pull-request.zip
          ls

      - name: Deploy Preview
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID_DEVELOPMENT }}
          netlify deploy --prod > ./deployments.log

      - name: "Comment on PR"
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          result-encoding: string
          script: |
            const commentOnPr = require("path").join(${{github.workspace}}, ".github", "workflows", "comment-on-pr.js");
            console.log(process.cwd());
            return require("./".concat(commentOnPr))(github, context);
