name: Slither

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.4/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc
          pip3 install slither-analyzer

      - name: Test with Slither
        run: |
          yarn install
          cp -rf node_modules/@openzeppelin packages/contracts/dollar/node_modules
          cp -rf node_modules/@openzeppelin packages/contracts/ubiquistick/node_modules
          cp -rf node_modules/@uniswap packages/contracts/dollar/node_modules
          cp -rf node_modules/solidity-linked-list packages/contracts/dollar/node_modules
          cd packages/contracts/dollar
          yarn slither
          cd ../ubiquistick
          yarn slither