name: Spell Check
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Spell Check
        run: |
          LIST="$(find . -type f \\( -name '*.sol' -o -name '*.tsx' -o -name '*.ts' \\) ! -path '*/node_modules/*' ! -path '*/lib/*' ! -path '*/types/*')"
          yes | npx cspell $LIST
