name: Spell Check
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Spell Check
        run: |
          TARGET=$(git diff --name-only $(GITHUB_BASE_REF)..$(GITHUB_HEAD_REF))
          yes | npx cspell $TARGET