name: Spell Check
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Checkout
        uses: actions/checkout@v3
        run: |
          git fetch --no-tags --prune --depth=1 origin "+refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}"
          CHANGES=$(git diff --name-only ${GITHUB_BASE_REF}..${GITHUB_HEAD_REF})
          yes | npx cspell --file-list $CHANGES
