name: Spell Check
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6

      - name: Spell Check
        run: |
          yes | npx cspell --file-list ${{ steps.changed-files.outputs.all_changed_files }}
