name: Generate Test Coverage Report

on:
  pull_request:
  push:
  create:
    tag:
      - "v*"

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Forge Install
        run: yarn workspace @ubiquity/contracts forge install

      - name: Run Forge tests
        run: yarn workspace @ubiquity/contracts forge install

      - name: Coverage
        run: yarn workspace @ubiquity/contracts forge install