name: Generate Test Coverage Report

on:
  pull_request:
  push:
  create:
    tag:
      - "v*"

jobs:
  jobA:
    strategy:
      fail-fast: true

    outputs:
      lines: ${{ steps.coverage.outputs.test }}

    name: Calculate Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: sudo apt -y update && sudo apt -y install libusb-1.0-0-dev libudev-dev

      - name: Setup Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install
        run: yarn install --mode=skip-build && yarn allow-scripts

      - name: Forge Install
        run: yarn workspace @ubiquity/contracts forge install

      - name: Coverage
        run: yarn workspace @ubiquity/contracts forge coverage --fork-url https://eth-mainnet.g.alchemy.com/v2/WRRZczVcOh7GrDm7TeE7PwfVayvnXWe7 > coverage.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cov-result
          path: ./coverage.txt
          
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    name: Update Coverage
    steps:
      - name: Download Coverage Results
        uses: actions/download-artifact@v3
        with:
          name: cov-result
      - shell: bash
        run: |
          tail -1 coverage.txt

